# Generated by Django 6.0.2 on 2026-02-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_customuser_is_approved_customuser_license_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('user', 'User')], default='user', max_length=20),
        ),
    ]
