# Generated by Django 6.0.2 on 2026-02-28 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('symptom_checker', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
