# Generated by Django 6.0.3 on 2026-03-12 17:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_healthlog_options_remove_healthlog_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='healthlog',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='one_log_per_day_per_user'),
        ),
    ]
