# Generated by Django 6.0.2 on 2026-03-06 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='communityaccesstag',
            new_name='community_c_user_id_358966_idx',
            old_name='community_co_user_id_6f4f77_idx',
        ),
        migrations.RenameIndex(
            model_name='communityaccesstag',
            new_name='community_c_user_id_75310c_idx',
            old_name='community_co_user_id_2a09d3_idx',
        ),
        migrations.RenameIndex(
            model_name='communityaccesstag',
            new_name='community_c_tag_cod_b06f7e_idx',
            old_name='community_co_tag_cod_60229a_idx',
        ),
        migrations.RenameIndex(
            model_name='communitymessage',
            new_name='community_c_room_id_f4e2a8_idx',
            old_name='community_co_room_id_be0e1d_idx',
        ),
        migrations.RenameIndex(
            model_name='communitymessage',
            new_name='community_c_user_id_d10105_idx',
            old_name='community_co_user_id_86f03f_idx',
        ),
        migrations.RenameIndex(
            model_name='symptomchecksnapshot',
            new_name='community_s_user_id_e66083_idx',
            old_name='community_sy_user_id_e7fa6f_idx',
        ),
        migrations.RenameIndex(
            model_name='symptomchecksnapshot',
            new_name='community_s_user_id_8a3080_idx',
            old_name='community_sy_user_id_2f2fd8_idx',
        ),
        migrations.RenameIndex(
            model_name='symptomchecksnapshot',
            new_name='community_s_user_id_bc21bd_idx',
            old_name='community_sy_user_id_2af4be_idx',
        ),
    ]
